export const SKILL_SUGGESTIONS = [
  // Technical Skills
  "JavaScript",
  "React",
  "Node.js",
  "Python",
  "TypeScript",
  "Java",
  "SQL",
  "AWS",
  "Docker",
  "Kubernetes",
  "Machine Learning",
  "Data Science",
  "DevOps",
  "Agile",
  "Product Management",
  "UI/UX Design",
  "GraphQL",
  "REST API",
  "C++",
  "C#",
  "Ruby",
  "PHP",
  "Go",
  "Rust",
  "HTML",
  "CSS",
  "Sass",
  "Bootstrap",
  "Tailwind CSS",
  "Jenkins",
  "CI/CD",
  "Terraform",
  "Ansible",
  "Linux",
  "Cloud Computing",
  "GCP",
  "Azure",
  "Big Data",
  "Hadoop",
  "Apache Spark",
  "ElasticSearch",
  "MongoDB",
  "PostgreSQL",
  "NoSQL",
  "Firebase",
  "Redux",
  "Next.js",
  "NestJS",
  "Spring Boot",
  "Hibernate",
  "Flask",
  "Django",
  "Ruby on Rails",
  "TensorFlow",
  "PyTorch",
  "OpenCV",
  "NLP",
  "AI",
  "Data Visualization",
  "Tableau",
  "Power BI",
  "MATLAB",
  "Blockchain",
  "Smart Contracts",
  "Web3.js",
  "Solidity",
  "Cybersecurity",
  "Penetration Testing",
  "Ethical Hacking",
  "Cryptography",
  "Information Security",
  "IoT",
  "Mobile Development",
  "Swift",
  "Kotlin",
  "Flutter",
  "React Native",
  "Game Development",
  "Unity",
  "Unreal Engine",
  "Testing",
  "Selenium",
  "Jest",
  "Mocha",
  "Chai",
  "Version Control",
  "Git",
  "GitHub",
  "GitLab",
  "Protocol Design",
  "System Design",
  "Performance Tuning",
  "Database Optimization",
  "ETL",
  "Data Engineering",

  // Soft Skills
  "Communication",
  "Teamwork",
  "Problem Solving",
  "Critical Thinking",
  "Adaptability",
  "Creativity",
  "Emotional Intelligence",
  "Conflict Resolution",
  "Time Management",
  "Organization",
  "Leadership",
  "Empathy",
  "Collaboration",
  "Negotiation",
  "Decision-Making",
  "Public Speaking",
  "Active Listening",
  "Networking",
  "Stress Management",
  "Work Ethic",

  // Non-Technical Skills and Domains
  "Market Research",
  "Business Analysis",
  "Strategic Planning",
  "Financial Management",
  "Sales",
  "Customer Relationship Management",
  "Marketing",
  "Digital Marketing",
  "SEO",
  "Content Writing",
  "Copywriting",
  "Graphic Design",
  "Video Editing",
  "Photography",
  "Event Planning",
  "Teaching",
  "Coaching",
  "Mentoring",
  "Languages",
  "Translation",
  "Cultural Awareness",
  "Legal Compliance",
  "Project Management",
  "Scrum Master",
  "Risk Assessment",
  "Data Entry",
  "Technical Writing",
  "Operations Management",
  "Supply Chain Management",
  "Logistics",
  "Quality Assurance",
  "Healthcare",
  "Education",
  "Psychology",
  "Human Resources",
  "Recruitment",
  "Onboarding",
  "Training and Development",
];
